micronaut:
  application:
    name: hackathonOccd20211112Team1
  server:
      cors:
        enabled: true
        configurations:
          web:
            allowedOrigins:
              - http://localhost:8080
              - http://localhost:8081
              - http://localhost:8082
              - http://localhost:8083
              - http://localhost:8084
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

jackson:
  serialization:
    writeDatesAsTimestamps: false

endpoints:
  health:
    enabled: true
    sensitive: false # non-secured endpoint
    details-visible: ANONYMOUS # show details for everyone

datasources:
  default:
    url: jdbc:h2:file:~/devDb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: ''
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true