CREATE TABLE CHARGING_SESSION (

    ID SERIAL PRIMARY KEY,
    ID_TAG VARCHAR(250),
    TRANSACTION_ID INTEGER,
    START_METER INTEGER,
    STOP_METER INTEGER,
    CHARGING_START TIMESTAMP,
    CHARGING_END TIMESTAMP

);