CREATE TABLE CHARGING_SESSION (

    ID INTEGER PRIMARY KEY,
    ID_TAG INTEGER,
    TRANSACTION_ID INTEGER,
    START_METER INTEGER,
    STOP_METER INTEGER,
    CHARGING_START TIMESTAMP,
    CHARGING_END TIMESTAMP

);